### ISSUE TITLE
Postgres version bug at CreateInsertWithOutput

### ISSUE THREAD

**Issue by Totopolis** [gerakul/FastSql#4]
DB
==
CREATE TABLE ""Board"" (
	""Id"" SERIAL PRIMARY KEY,
	""Created"" DATE,
	""Modified"" DATE,
	""Name"" VARCHAR(255)
);

C#
==
var board = new DboBoard()
{
Created = DateTime.Now,
Modified = DateTime.Now,
Name = name
};

// work
context.Insert("Board", board, "Id");
            
// not work
board.Id = context
                .CreateInsertWithOutput("Board", board, "Id", "Id")
                .ExecuteQueryFirstColumn<int>()
                .First();

// expect autoincrement at CreateInsertWithOutput

Thanx.

**Comment by gerakul** [comment]
The proper way to do that:
  ```csharp
    board.Id = context
        .CreateInsertWithOutput("Board", board, new[] { "Id" }, "Id")
        .ExecuteQueryFirstColumn<int>()
        .First();
  ```
So, this is not a program error. This is rather not the best design.

**Comment by Totopolis** [comment]
yes, it works, thanks!
